export type ErrorStatus =
    | 'USER_ALREADY_EXISTS'
    | 'USER_NOT_FOUND'
    | 'USER_NOT_ACTIVE'
    | 'ILLEGAL_STATE'
    | 'STUDENT_PROFILE_ALREADY_EXISTS'
    | 'STUDENT_PROFILE_NOT_FOUND'
    | 'TUTOR_PROFILE_ALREADY_EXISTS'
    | 'TUTOR_PROFILE_NOT_FOUND'
    | 'PROFILE_ALREADY_EXISTS'
    | 'INVALID_PROFILE_TYPE'
    | 'AUTHENTICATION_FAILED'
    | 'AUTH_ACCESS_DENIED'
    | 'VERIFICATION_TOKEN_NOT_FOUND'
    | 'VERIFICATION_TOKEN_EXPIRED'
    | 'VERIFICATION_TOKEN_ALREADY_CONFIRMED'
    | 'VERIFICATION_TOKEN_ALREADY_USED'
    | 'JWT_MALFORMED'
    | 'JWT_EXPIRED'
    | 'JWT_UNSUPPORTED'
    | 'REFRESH_TOKEN_NOT_FOUND'
    | 'REFRESH_TOKEN_NOT_PROVIDED'
    | 'SUBJECT_ALREADY_EXISTS'
    | 'SUBJECT_NOT_FOUND'
    | 'INVALID_PROPOSED_TIME'
    | 'AVAILABLE_SLOT_NOT_FOUND'
    | 'UNAVAILABLE_SLOT'
    | 'SLOT_RESERVED'
    | 'AVAILABLE_SLOT_ALREADY_STARTED'
    | 'INVALID_SLOT_STATUS'
    | 'LESSON_OVERLAPPING'
    | 'NO_LESSONS'
    | 'LESSON_DOES_NOT_EXITS'
    | 'ERROR_INTERNAL_SERVER'
    | 'ERROR_BAD_REQUEST'
    | 'ENTITY_NOT_FOUND'

export type ApiResponse<T> = {
    ok: boolean
    data: T | null
    message: string
    errorStatus: ErrorStatus | null
}